/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "project-beacon_loc-0ISfeUp-V-i9ZsSuDqcYDiNNtZwUPYWI",
  "version": "2020-11-20"
}

export default ebconfig;